Story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('exp/', views.exp, name='exp'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

def exp(request):
    return render(request, 'main/exp.html')

def gallery(request):
    return render(request, 'main/gallery.html')

def contact(request):
    return render(request, 'main/contact.html')

main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-default">
        <a class="navbar-brand" href="#">Contact</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ">
            <a class="nav-link" href="{% url 'main:index' %}">Profile <span class="sr-only">(current)</span></a>
            <a class="nav-link " href="{% url 'main:exp' %}">Experience</a>
            <a class="nav-link" href="{% url 'main:gallery' %}">Gallery</a>
            <a class="nav-link active" href="#">Contact</a>
          </div>
        </div>
      </nav>
      <div class="container cntct">
            <h3 class="text-center">You</h3>
            <h3 class="text-center">can</h3>
            <h3 class="text-center">contact</h3>
            <h3 class="text-center">me</h3>
            <h3 class="text-center">through</h3>
            <br>
            <a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=memahafizh@gmail.com&tf=1"><img src="{% static 'img/gmail.png' %}"></a>
            <br>
            <a href="https://www.instagram.com/memahafizh/"><img src="{% static 'img/ig.png' %}"></a>
            <br>
            <a href="https://www.linkedin.com/in/mohammad-hafizh-dwiandra-ramadhan-5251231a3/"><img src="{% static 'img/linkedin.png' %}"></a>
            <br>
            <a href="https://vsco.co/memahafizh/gallery"><img src="{% static 'img/vsco.jpeg' %}"></a>
      </div>
{% endblock content %}

main/templates/main/exp.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-default">
        <a class="navbar-brand" href="#">Experience</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ">
            <a class="nav-link" href="{% url 'main:index' %}">Profile <span class="sr-only">(current)</span></a>
            <a class="nav-link active" href="#">Experience</a>
            <a class="nav-link" href="{% url 'main:gallery' %}">Gallery</a>
            <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-md-4 compfest">
            <img class="cmpfst" src="{% static 'img/logocompfest-removebg-preview.png' %}" style="width: 270px;height: 270px;background-color: black;margin-top: 1.5vh;margin-left: 1.5vh;max-width: 92%;height: auto;">
            <br>
            <br>
            <h4>Compfest 12</h4>
            <h5>2020</h5>
            <p>Staff of Stage Division</p>
          </div>
          <div class="col-md-2">
          </div>
          <div class="col-md-4 perak">
            <img class="prk" src="{% static 'img/perak-removebg-preview.png' %}" style="width: 270px;height: 270px;background-color: white;margin-top: 1.5vh;margin-left: 1.5vh;max-width: 92%;height: auto;">
            <br>
            <br>
            <h4>Pesta Rakyat Komputer Fasilkom</h4>
            <h5>2020</h5>
            <p>Staff of Games Division</p>
          </div>
          </div>
        </div>
      </div>
    {% endblock content %}

main/templates/main/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-default">
        <a class="navbar-brand" href="#">Gallery</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ">
            <a class="nav-link" href="{% url 'main:index' %}">Profile <span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'main:exp' %}">Experience</a>
            <a class="nav-link active" href="#">Gallery</a>
            <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
          </div>
        </div>
      </nav>
      <div class="container gal">
        <h2 style="padding: 10px;">Hi!</h2>
        <p style="padding-left: 10px;">Here are some pictures taken and edited by me.</p>
        <p style="padding-left: 10px;">Enjoy!</p>
        <div class="row">
            <div class="col-md-12">
                <div class="thumbnail">
                    <a href="https://vsco.co/memahafizh/media/5b4cb7342c63de1762000001" target="_blank"><img src="{% static 'img/hihor.jpg' %}" alt="Bundaran HI, Indonesia, 2018" style="width: 100%;"></a>
                        <div class="caption">
                            <p>Bundaran HI, Indonesia, 2018</p>
                        </div>
                </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="thumbnail">
              <a href="https://vsco.co/memahafizh/media/5cbd721b2e637b4d2d000001" target="_blank"><img src="{% static 'img/hiver.jpg' %}" alt="Bundaran HI, Indonesia, 2019" style="width:100%"></a>
                <div class="caption">
                  <p>Bundaran HI, 2019</p>
                </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <a href="https://vsco.co/memahafizh/media/5f7878792e637b0366000001" target="_blank"><img src="{% static 'img/senayanver.jpg' %}" alt="Sudirman, Indonesia, 2019" style="width:100%"></a>
                <div class="caption">
                  <p>Sudirman, Indonesia, 2019</p>
                </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="thumbnail">
              <a href="https://vsco.co/memahafizh/media/5a41fe7214aee2081d000001" target="_blank"><img src="{% static 'img/mbsver.jpg' %}" alt="Marina Bay Sands, Singapore, 2017" style="width:100%"></a>
                <div class="caption">
                  <p>Marina Bay Sands, Singapore, 2017</p>
                </div>
            </div>
          </div>
        </div>
        <div class="row">
            <div class="col-md-12">
              <div class="thumbnail">
                <a href="https://vsco.co/memahafizh/media/5a4289f314aee246cd000009" target="_blank"><img src="{% static 'img/mbshor.jpg' %}" alt="National Gallery, Singapore, 2017" style="width:100%"></a>
                  <div class="caption">
                    <p>National Gallery, Singapore, 2017</p>
                  </div>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="container more">
                <p>For more, visit <a href="https://vsco.co/memahafizh/gallery" class="here" target="_blank">here</a></p>
            </div>
        </div>
    </div>
    {% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mohammad Hafizh Dwiandra R</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock meta %}

{% block content %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-default">
        <a class="navbar-brand" href="#">Profile</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ">
            <a class="nav-link active" href="#">Profile <span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'main:exp' %}">Experience</a>
            <a class="nav-link" href="{% url 'main:gallery' %}">Gallery</a>
            <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
          </div>
        </div>
      </nav>
      <br>
      <p><img src="{% static 'img/saya.png' %}"alt="Myself bruh" style="float:left;height:400px;margin-right: 3vw;margin-left:40px;margin-top: 100px;margin-bottom: 3vw;"></p>
      <div class="bio">
        <p>Nama: Mohammad Hafizh Dwiandra Ramadhan</p>
        <p>NPM: 1906398383</p>
        <p>Angkatan: 2019</p>
        <p>Hobi: Mencari waktu luang</p>
        <p>Deskripsi: Friendly</p>
        <p>Tempat Kuliah: Fasilkom UI</p>
        <p>Riwayat Pendidikan:
            <table style="width:50%">
                <tr>
                  <th>Jenjang</th>
                  <th>Nama Sekolah</th> 
                  <th>Tahun Studi</th>
                </tr>
                <tr>
                  <td>SD</td>
                  <td>Bhakti YKKP</td>
                  <td>2006-2013</td>
                </tr>
                <tr>
                  <td>SMP</td>
                  <td>Labschool Kebayoran</td>
                  <td>2013-2016</td>
                </tr>
                <tr>
                  <td>SMA</td>
                  <td>Labschool Kebayoran</td>
                  <td>2016-2019</td>
                </tr>
              </table>
        </p>
        </div>
      {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block meta %}
  {% endblock meta %}
  <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>

<body>
</body>
  {% block content %}
  {% endblock content %}
</html>